HAI 1.2
CAN HAS STDIO?

HOW IZ I FEBONACCII YR NOMBUR
    BOTH SAEM NOMBUR AN SMALLR OF NOMBUR AN 1, O RLY?
        YA RLY
            FOUND YR NOMBUR
        NO WAI
             FOUND YR SUM OF I IZ FEBONACCII YR DIFF OF NOMBUR AN 1 MKAY AN I IZ FEBONACCII YR DIFF OF NOMBUR AN 2 MKAY
    OIC
IF U SAY SO

I HAS A VAR ITZ 1

IM IN YR RECURR UPPIN YR VAR TIL BOTH SAEM VAR AN 10
    VISIBLE I IZ FEBONACCII YR VAR MKAY
IM OUTTA YR RECURR
    
    
KTHXBYE

